/* ===== players ===== */
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 1,  '1', 1,  'ローマン・ヴァイデンフェラー');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 3,  '2', 27, '朴柱昊');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 4,  '2', 10, 'ネヴェン・スボティッチ');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 6,  '3', 1,  'スヴェン・ベンダー');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 8,  '3', 1,  'イルカイ・ギュンドアン');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 10, '3', 67, 'ヘンリク・ムヒタリアン');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 11, '4', 1,  'マルコ・ロイス');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 13, '2', 68, 'ジョン・ゴレンシ・スタンコビッチ');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 14, '3', 1,  'モリッツ・ライトナー');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 15, '2', 1,  'マッツ・フメルス');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 17, '3', 69, 'ピエール＝エメリク・オーバメヤン');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 18, '3', 9,  'ヌリ・シャヒン');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 20, '4', 62, 'アドリアン・ラモス');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 22, '3', 16, 'クリスチャン・プリシッチ');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 23, '3', 8,  '香川真司');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 24, '2', 1,  'マリアン・ザー');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 25, '2', 12, 'ソクラティス・パパスタソプーロス');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 26, '2', 14, 'ウカシュ・ピシュチェク');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 27, '3', 1,  'ゴンサロ・カストロ');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 28, '2', 1,  'マティアス・ギンター');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 29, '2', 1,  'マルセル・シュメルツァー');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 30, '3', 1,  'フェリックス・パスラック');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 33, '3', 1,  'ユリアン・ヴァイグル');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 34, '4', 1,  'マーヴィン・ドゥクシュ');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 37, '2', 1,  'エリック・ドゥルム');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 38, '1', 4 , 'ロマン・ビュルキ');
insert into players(created_at, squad_number, position_code, nationality_id, name) values(current_timestamp, 39, '1', 1,  'ヘンドリック・ボンマン');
